lesson01/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson01/myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

lesson01/myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="register"),
    path('logout/', views.logout_view, name="logout"),
]

lesson01/myproject/posts/models.py
from django.db import models

class Post(models.Model):
  title = models.CharField(max_length=75)
  body = models.TextField()
  slug = models.SlugField() 
  date = models.DateTimeField(auto_now_add=True)
  banner = models.ImageField(default='fallback.png', blank=True)

  def __str__(self):
    return self.title

lesson01/myproject/users/models.py
from django.db import models

# Create your models here.

lesson01/myproject/myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
  # return HttpResponse("Hey Fam, I'm Home.")
  return render(request, 'home.html')

def about(request):
  # return HttpResponse("About Me!")
  return render(request, 'about.html')

lesson01/myproject/posts/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.
def posts_list(request):
  posts = Post.objects.all().order_by('-date')
  return render(request, 'posts/posts_list.html', { 'posts': posts})

def post_page(request, slug):
  post = Post.objects.get(slug=slug)
  return render(request, 'posts/post_page.html', { 'post': post})

@login_required(login_url="/users/login/")
def post_new(request):
  return render(request, 'posts/post_new.html')

lesson01/myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def login_view(request):
  if request.method == "POST":
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
      login(request, form.get_user())
      if 'next' in request.POST:
        return redirect(request.POST.get('next'))
      else:
        return redirect("posts:list")
  else: 
    form = AuthenticationForm()
  return render(request, 'users/user_login.html', { "form" : form })

def register_view(request):
  if request.method == "POST":
    form = UserCreationForm(request.POST)
    if form.is_valid():
      login(request, form.save())
      return redirect("posts:list")
  else: 
    form = UserCreationForm()
  return render(request, 'users/register_page.html', { "form":form })

def logout_view(request):
  if request.method == "POST":
    logout(request)
    return redirect("posts:list")

lesson01/myproject/posts/templates/posts/post_new.html
<!-- prettier-ignore -->
{% extends 'layout.html' %} 
{% block title %} 
  New Post
{% endblock %} 
{% block content %}
<section>
	<h1>New Post</h1>
</section>
{% endblock %}

lesson01/myproject/posts/templates/posts/post_page.html
<!-- prettier-ignore -->
{% extends 'layout.html' %} 
{% block title %} 
  {{ post.title }}
{% endblock %} 
{% block content %}
<section>
	<h1>{{ post.title }}</h1>
	<p>{{ post.body }}</p>
	<img class="banner" src="{{post.banner.url}}" alt="{{post.title}}" />
	<p class="timestamp">{{ post.date }}</p>
	<p>Return to <a href="/posts">posts</a> page.</p>
</section>
{% endblock %}

lesson01/myproject/posts/templates/posts/posts_list.html
<!-- prettier-ignore -->
{% extends 'layout.html' %} 
{% block title %} 
	Posts 
{% endblock %} 
{% block content %}
<section>
	<h1>Posts</h1>

	{% for post in posts %}
	<article class="post">
		<h2>
			<a href="{% url 'posts:page' slug=post.slug %}"> {{ post.title }} </a>
		</h2>
		<p class="timestamp">{{ post.date }}</p>
		<p>{{ post.body }}</p>
	</article>
	{% endfor %}
</section>
{% endblock %}

lesson01/myproject/templates/about.html
<!-- prettier-ignore -->
{% extends 'layout.html' %} 
{% block title %} 
	About 
{% endblock %} 
{% block content %}
<h1>About</h1>
<p>Check out my <a href="/">home</a> page.</p>
{% endblock %}

lesson01/myproject/templates/home.html
<!-- prettier-ignore -->
{% extends 'layout.html' %} 
{% block title %} Home {% endblock %} 
{% block content %}
<h1>Home</h1>
<p>Check out my <a href="/about">about</a> page.</p>
{% endblock %}

lesson01/myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{% block title %} Django App {% endblock %}</title>
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<script src="{% static 'js/main.js' %}" defer></script>
	</head>
	<body>
		<nav>
			<a href="/"> <span role="img" aria-label="Home" title="Home">🏠</span></a>
			|
			<a href="/about">
				<span role="img" aria-label="About" title="About"> 😁 </span></a
			>
			|
			<a href="{% url 'posts:list' %}">
				<span role="img" aria-label="Posts" title="Posts">📰</span></a
			>
			|
			<!-- prettier-ignore -->
			{% if user.is_authenticated %}
			<a href="{% url 'posts:new-post' %}">
				<span role="img" aria-label="New Post" title="New Post">🆕</span></a
			>
			|
			<form class="logout" action="{% url 'users:logout' %}" method="post">
				<!-- prettier-ignore -->
				{% csrf_token %}
				<!-- prettier-ignore -->
				<button class="logout-button" aria-label="User Logout Button" title="User Logout Button">👋</button>
			</form>
			<!-- prettier-ignore -->
			{% else %}
			<a href="{% url 'users:login' %}">
				<span role="img" aria-label="User Login" title="User Login">👤</span></a
			>

			<!-- prettier-ignore -->
			{% endif %}
		</nav>

		<main>{% block content %}{% endblock %}</main>
	</body>
</html>

lesson01/myproject/users/templates/users/register_page.html
<!-- prettier-ignore -->
{% extends 'layout.html' %} 
{% block title %} 
	Users | Register 
{% endblock %} 
{% block content %}
<h1>Sign Up!</h1>
<form action="/users/register/" method="post">
	<!-- prettier-ignore -->
	{% csrf_token %}
	<!-- prettier-ignore -->
	{{ form }}
	<button>Submit</button>
</form>
{% endblock %}

lesson01/myproject/users/templates/users/user_login.html
<!-- prettier-ignore -->
{% extends 'layout.html' %} 
{% block title %} 
	User Login 
{% endblock %} 
{% block content %}
<h1>User Login</h1>
<form action="/users/login/" method="post">
	<!-- prettier-ignore -->
	{% csrf_token %}
	<!-- prettier-ignore -->
	{{ form }}
	<!-- prettier-ignore -->
	{% if request.GET.next %}
	<input type="hidden" name="next" value="{{request.GET.next}}" />
	{% endif %}
	<button>Submit</button>
</form>
<p>Not a User? Click to <a href="{% url 'users:register' %}">Sign Up!</a></p>
{% endblock %}